general {
    output_format = "i3bar"
    colors = true
    interval = 5          # Atualiza a cada 5 segundos
}

# Ordem dos módulos exibidos (da esquerda para a direita)
order += "cpu_usage"
order += "memory"
order += "time"

# Mostra uso de CPU
cpu_usage {
    format = "CPU: %usage"
}

# Mostra uso de memória RAM
memory {
    format = "RAM: %used / %total"
    threshold_degraded = "10%"
    format_degraded = "MEMORY: %free"
}


# Mostra data e hora (no padrão do i3)
time {
    format = "%Y-%m-%d %H:%M:%S"
}
